name: Docker Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # Node 24를 정식 지원하는 v4.2.2 이상의 최신 배포판을 사용합니다.
      uses: actions/checkout@v4.2.2 

    - name: Set up Python
      # setup-python 역시 최신 마이너 버전을 사용합니다.
      uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.11'

    - name: Build Flask Docker image
      run: docker image build -t myflask-test .

    - name: Run Flask Docker container
      run: docker container run -d --name myflask-ac -p 8001:8001 myflask-test

    - name: Test Flask app
      run: |
        sleep 10
        curl http://127.0.0.1:8001

    - name: Stop and remove Docker container
      run: |
        docker container stop myflask-ac
        docker container rm myflask-ac
